# Generated by Django 2.2.2 on 2021-07-07 03:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscribes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('acept', models.BooleanField(default=False, verbose_name='Aceptar')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de cración')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-created_date'],
            },
        ),
    ]
